### PR TITLE
Fix shmem_test arguments in osh_basic_tc7.c

### PR DESCRIPTION
**Pull request by davidozog**
This is a proposed fix for SOS issue [#791](https://github.com/Sandia-OpenSHMEM/SOS/issues/791) in reference to this comment:
https://github.com/openshmem-org/tests-mellanox/commit/50a19a296994e37d2352db0643fd056c0739e5a8#r31152661

Signed-off-by: David M. Ozog <david.m.ozog@intel.com>

### CODE REVIEW

**Comment by jdinan** [comment]
It would be super helpful if we could merge this fix.  As noted above, this issue is causing our CI and nightly testing systems to fail on the Mellanox tests.

**Comment by jdinan** [comment]
@yosefe Looks like this is an update to one of your recent edits.

**Comment by jdinan** [comment]
FWIW, lookin a little deeper at this test, it appears to have undefined behavior when the number of PEs is greater than two, since multiple PEs will `shmem_p` to the same variable at PE 0 concurrently.

**Comment by davidozog** [comment]
@miked-mellanox @hoopoepg or @yosefe could you please review this when you have a chance?

It's just a matter of the argument ordering (see 9.9.2 of the v1.4 OpenSHMEM specification).  I've updated this PR to make it as minimal a change as possible.

**Comment by yosefe** [comment]
ok to test

**Pull request merged**
