### PR TITLE
TEST/LOCK: fixed hang in oshmem over shm transports

### PR DESCRIPTION
**Pull request by hoopoepg**
- in case when SHM based transports were used test may
  hang due to missing progress call

fixes https://github.com/openucx/ucx/issues/4447

### CODE REVIEW

**Comment by jdinan** [comment]
Put/Get are not guaranteed by the OpenSHMEM specification to be atomic, even at the level of a single byte. For example, an implementation (none that I know of do this for such a small message, but it's allowed) could write a corrupted value to memory before performing a CRC check and retransmitting. Why not use atomic fetch/set instead?

**Comment by hoopoepg** [comment]
this issue is bit different: there are deadlock between 2 peers due to missing progress call. as I can see this test is not "real lock/unlock", it is just stress test for communications

**Comment by jdinan** [comment]
Yeah, sorry about the off topic comment, I know that's not what you were setting out to fix. For what it's worth, the explicit progress calls also highlight another spec compliance issue..

**Comment by hoopoepg** [comment]
no problemo
actually this is implementation-specific issue: UCX used SW emulation to access remote memory, issue is not actual when HW RDMA used

**Comment by hoopoepg** [comment]
@yosefe ok to merge?

**Comment by yosefe** [comment]
@jdinan i agree that this test is not fully spec-compliant

**Pull request merged**
