### PR TITLE
Make mix tests optional

### PR DESCRIPTION
**Pull request by davidozog**
This addresses #20 by adding --enable-mpi / --disable-mpi flag to configure.

### CODE REVIEW

**Comment by miked-mellanox** [comment]
@davidozog - could you please squash commits.
we are connecting jenkins CI to this project, hope it will be operational next week to smoke test & review it.
@MrBr-github

**Comment by jdinan** [comment]
@miked-mellanox You should be able to squash when you merge the commit by clicking the down arrow on the right side of the merge button and selecting "Squash and merge".

**Comment by davidozog** [comment]
@miked-mellanox Would you prefer that I "push --force" a squashed commit to this PR, open a new PR, or let you do the green-button "squash and merge"?  I'm fine with whatever you prefer.

**Comment by ireed** [comment]
I was unaware that you were working on the MPI separation, and i was preparing a pull-request until i checked here. 
I have a proposed version that auto-configures based on the existence/detection of -lmpi instead of depending on a hard-coded define. This method follows the style of the original architect(s).

https://github.com/ireed/tests-mellanox/commit/aeadfd424d506e0e783f10d1715d374ac7691d2a

**Comment by jdinan** [comment]
I think the explicit ```--disable-mpi``` option will work better.  It's common to have MPI installed in the development environment; however, the OpenSHMEM build may still not support mixed mode operation.

MPI also does not have a standard library name, so checking for ```libmpi``` is not sufficient to detect MPI.  Something like this would be more robust:
```
AC_COMPILE_IFELSE([#include <mpi.h>
int main(void) { MPI_Init(NULL, NULL); MPI_Finalize(); return 0; }], ...)
```

**Comment by miked-mellanox** [comment]
ok to test

**Comment by miked-mellanox** [comment]
bot:retest

**Comment by miked-mellanox** [comment]
@davidozog - merge conflict

**Pull request merged**
